name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Make Docker Build
      run: make docker-build
